# Generated by Django 4.2 on 2023-04-16 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0002_alter_film_id_alter_zanr_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pojisteni',
            name='film',
        ),
        migrations.AddField(
            model_name='film',
            name='pojisteni',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientapp.pojisteni'),
        ),
    ]
