# Generated by Django 4.2 on 2023-04-21 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0004_remove_film_zanr_zanr_film'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={'verbose_name': 'Klient', 'verbose_name_plural': 'Filmy'},
        ),
        migrations.AlterModelOptions(
            name='pojisteni',
            options={'verbose_name': 'Žánr', 'verbose_name_plural': 'Žánry'},
        ),
        migrations.RemoveField(
            model_name='pojisteni',
            name='film',
        ),
        migrations.AddField(
            model_name='film',
            name='pojisteni',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientapp.pojisteni', verbose_name='Žánr'),
        ),
        migrations.AlterField(
            model_name='film',
            name='nazev',
            field=models.CharField(max_length=200, verbose_name='Název Filmu'),
        ),
        migrations.AlterField(
            model_name='film',
            name='pojistovna',
            field=models.CharField(max_length=180, verbose_name='Režie'),
        ),
        migrations.AlterField(
            model_name='pojisteni',
            name='nazev_pojisteni',
            field=models.CharField(max_length=80, verbose_name='Žánr'),
        ),
    ]
